### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by DMario93** [Mayachitra-Inc/MaleX#4]
Importing the encrypted files fails with python 3.6, 3.7, 3.10.1 and using the sourcedefender version specified in the requirements.txt (7.1.61).

output:

```ipython-input-2-7624ff647815> in <module>
----> 1 from get_byteplot_image import *

src/pyx/loader.pyx in loader.MetaLoader.exec_module()

ImportError: ImportError: get_byteplot_image.pye
```

Special thanks to whomever will help me :)

**Comment by mc-manhar** [comment]
Issue fixed! Replaced SOURCEdefender parts with byte-compiled versions of the same.
