### ISSUE TITLE
problem in importing .pyc files

### ISSUE THREAD

**Issue by mohsen-1389** [Mayachitra-Inc/MaleX#5]
hi, when i want to import *pyc modules i have below error:

from get_byteplot_image import *
from get_bigram_dct_image import *
### ImportError: bad magic number in 'get_byteplot_image': b'U\r\r\n'

it seems its because of different python versions. what was your python version when you compiled *.pyc files?

**Comment by mohsen-1389** [comment]
it seems its python version is 3.8. I changed my python version to 3.8 and it works fine!

**Comment by mc-manhar** [comment]
Thanks for pointing this out! I have fixed this in the commit [dab73221a55f8bd3ebb981a38c255e4098dbdf29](https://github.com/Mayachitra-Inc/MaleX/tree/dab73221a55f8bd3ebb981a38c255e4098dbdf29), which should now support Python 3.8, 3.9 and 3.10.
