### ISSUE TITLE
I can't send the message from the website https://mayachitra.com/#contact-us

### ISSUE THREAD

**Issue by Andexrian** [Mayachitra-Inc/MaleX#6]
I have complied with all message length and attachment constraints, but when I try to send a message from your website, with an attachment for the MaleX dataset request, the request remains pending indefinitely.

**Comment by mc-manhar** [comment]
We've successfully shared the dataset with numerous users who completed the request form without encountering similar issues, so it's surprising to hear about your experience. 

> Also, while filling out the form, please make sure that the message's character length is between 20 and 1000, and/or the PDF attachment is less than 2MB.

Please try again with and without attachments, if necessary. Make sure to include all the relevant details in your message.
